/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/restaurante/Mesas.gltf -r public
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useSelector } from 'react-redux';
import { MeshPhongMaterial } from 'three';

let mesaId = 9

export const mesa1 = new THREE.Group();
mesa1.userData.id = mesaId++
export const mesa2 = new THREE.Group();
mesa2.userData.id = mesaId++
export const mesa3 = new THREE.Group();
mesa3.userData.id = mesaId++
export const mesa4 = new THREE.Group();
mesa4.userData.id = mesaId++
export const mesa5 = new THREE.Group();
mesa5.userData.id = mesaId++
export const mesa6 = new THREE.Group();
mesa6.userData.id = mesaId++
export const mesa7 = new THREE.Group();
mesa7.userData.id = mesaId++
export const mesa8 = new THREE.Group();
mesa8.userData.id = mesaId++
export const mesa9 = new THREE.Group();
mesa9.userData.id = mesaId++
export const mesa10 = new THREE.Group();
mesa10.userData.id = mesaId++
export const mesa11 = new THREE.Group();
mesa11.userData.id = mesaId++
export const mesa12 = new THREE.Group();
mesa12.userData.id = mesaId++
export const mesa13 = new THREE.Group();
mesa13.userData.id = mesaId++
export const mesa14 = new THREE.Group();
mesa14.userData.id = mesaId++
export const mesa15 = new THREE.Group();
mesa15.userData.id = mesaId++
export const mesa16 = new THREE.Group();
mesa16.userData.id = mesaId++
export const mesa17 = new THREE.Group();
mesa17.userData.id = mesaId++
export const mesa18 = new THREE.Group();
mesa18.userData.id = mesaId++
export const mesa19 = new THREE.Group();
mesa19.userData.id = mesaId++
export const mesa20 = new THREE.Group();
mesa20.userData.id = mesaId++
export const mesa21 = new THREE.Group();
mesa21.userData.id = mesaId++
export const mesa22 = new THREE.Group();
mesa22.userData.id = mesaId++
export const mesa23 = new THREE.Group();
mesa23.userData.id = mesaId++
export const mesa24 = new THREE.Group();
mesa24.userData.id = mesaId++
export const mesa25 = new THREE.Group();
mesa25.userData.id = mesaId++
export const mesa26 = new THREE.Group();
mesa26.userData.id = mesaId++
export const mesa27 = new THREE.Group();
mesa27.userData.id = mesaId++
export const mesa28 = new THREE.Group();
mesa28.userData.id = mesaId++
export const mesa29 = new THREE.Group();
mesa29.userData.id = mesaId++
export const mesa30 = new THREE.Group();
mesa30.userData.id = mesaId++
export const mesa31 = new THREE.Group();
mesa31.userData.id = mesaId++
export const mesa32 = new THREE.Group();
mesa32.userData.id = mesaId++
export const mesa33 = new THREE.Group();
mesa33.userData.id = mesaId++
export const mesa34 = new THREE.Group();
mesa34.userData.id = mesaId++
export const mesa35 = new THREE.Group();
mesa35.userData.id = mesaId++
export const mesa36 = new THREE.Group();
mesa36.userData.id = mesaId++

export default function Mesas(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/restaurante/Mesas.gltf')
  const { tables, infoBooking } = useSelector(state => state)
  const { setSelectedMesaId, selectedMesaId, setErrorMessage, errorMessage, confirmSearchTables } = props
  const {confirmTable} = props
  const selectMaterial = new MeshPhongMaterial({ color: '#004f80' })
  const availableMaterial = new MeshPhongMaterial({ color: '#008000' });
  const selectTable = new MeshPhongMaterial({color: '#a3a21b'})
  const originalColor = new THREE.Color('#804000')

  const handleMesaClick = (id) => {
    if(confirmTable || !confirmSearchTables) {

      return;
    }
    const table = tables.find(table => table.id === id)
    if(table && table.availability){
      setSelectedMesaId(id)
      setErrorMessage('')
    } else {
      setErrorMessage('No puedes seleccionar esta mesa')
    }
  };

  const renderMesas = [
    mesa1, 
    mesa2, 
    mesa3, 
    mesa4, 
    mesa5, 
    mesa6, 
    mesa7, 
    mesa8, 
    mesa9, 
    mesa10, 
    mesa11, 
    mesa12, 
    mesa13, 
    mesa14, 
    mesa15, 
    mesa16, 
    mesa17, 
    mesa18, 
    mesa19, 
    mesa20, 
    mesa21, 
    mesa22, 
    mesa23, 
    mesa24, 
    mesa25, 
    mesa26, 
    mesa27, 
    mesa28, 
    mesa29, 
    mesa30, 
    mesa31, 
    mesa32, 
    mesa33, 
    mesa34, 
    mesa35, 
    mesa36
  ]

  useEffect(() => {
    renderMesas.forEach(mesa => {
      mesa.children.forEach(child => {
        if (child.isMesh) {
          // Restaurar el color del material a su valor original
          child.material.color.set(originalColor);
        }
      });
    });
  }, [])

  useEffect(() => {
    if (infoBooking.tableId) {
      renderMesas.forEach((mesa) => {
        if (mesa.userData.id === infoBooking.tableId) {
          mesa.children.forEach((child) => {
            if (child.isMesh) {
              child.material = selectTable;
          }});
        }
      });
    }
  }, [infoBooking.tableId]);


      let mesasDisponibles = []
  
      tables.forEach(table => {
        renderMesas.forEach(mesa => {
          if(table.id === mesa.userData.id && table.availability === true){
            mesa.children.forEach(child => {
              if(child.isMesh){
                child.material = availableMaterial
                mesasDisponibles.push(mesa)
              }
            })
          }
        });
      });
  
      renderMesas.forEach(mesa => {
        if(!mesasDisponibles.includes(mesa)){
          mesa.children.forEach(child => {
            if(child.isMesh){
              child.material.color.set('#FF0000')
            }
          })
        }
      });

      mesasDisponibles.forEach(disponible => {
        if(disponible.userData.id === selectedMesaId){
          disponible.children.forEach(child => {
            if(child.isMesh){
              child.material = selectMaterial
              if(errorMessage){
                child.material = availableMaterial
              } else {
                child.material = selectMaterial
              }
            }
          })
        } else {
          disponible.children.forEach(child => {
            if(child.isMesh){
              child.material = availableMaterial
            }
          })
        }
      });

  mesa1.add(nodes.Mesh6618_1248);
  mesa1.add(nodes.Mesh6618_1249);
  mesa1.add(nodes.Mesh6618_1250);
  mesa1.add(nodes.Mesh6618_1251);
  mesa1.add(nodes.Mesh6618_1252);
  mesa1.add(nodes.Mesh6618_1253);
  mesa1.add(nodes.Mesh6618_1254);
  mesa1.add(nodes.Mesh6618_1255);
  mesa1.add(nodes.Mesh6618_1256);
  mesa1.add(nodes.Mesh6618_1257);
  mesa1.add(nodes.Mesh6618_1258);
  mesa1.add(nodes.Mesh6618_1259);
  mesa1.add(nodes.Mesh6618_1260);
  mesa1.add(nodes.Mesh6618_1261);
  mesa1.add(nodes.Mesh6618_1262);
  mesa1.add(nodes.Mesh6618_1263);
  mesa1.add(nodes.Mesh6618_1264);
  mesa1.add(nodes.Mesh6618_1265);
  mesa1.add(nodes.Mesh6618_1266);
  mesa1.add(nodes.Mesh6618_1267);
  mesa1.add(nodes.Mesh6618_1268);
  mesa1.add(nodes.Mesh6618_1269);
  mesa1.add(nodes.Mesh6618_1270);
  mesa1.add(nodes.Mesh6618_1271);
 

  mesa2.add(nodes.Mesh6618_972);
  mesa2.add(nodes.Mesh6618_973);
  mesa2.add(nodes.Mesh6618_974);
  mesa2.add(nodes.Mesh6618_975);
  mesa2.add(nodes.Mesh6618_976);
  mesa2.add(nodes.Mesh6618_977);
  mesa2.add(nodes.Mesh6618_978);
  mesa2.add(nodes.Mesh6618_979);
  mesa2.add(nodes.Mesh6618_980);
  mesa2.add(nodes.Mesh6618_981);
  mesa2.add(nodes.Mesh6618_982);
  mesa2.add(nodes.Mesh6618_983);
  mesa2.add(nodes.Mesh6618_984);
  mesa2.add(nodes.Mesh6618_985);
  mesa2.add(nodes.Mesh6618_986);
  mesa2.add(nodes.Mesh6618_987);
  mesa2.add(nodes.Mesh6618_988);
  mesa2.add(nodes.Mesh6618_989);
  mesa2.add(nodes.Mesh6618_990);
  mesa2.add(nodes.Mesh6618_991);
  mesa2.add(nodes.Mesh6618_992);
  mesa2.add(nodes.Mesh6618_993);
  mesa2.add(nodes.Mesh6618_994);
  mesa2.add(nodes.Mesh6618_995);


  mesa3.add(nodes.Mesh6618_882);
  mesa3.add(nodes.Mesh6618_883);
  mesa3.add(nodes.Mesh6618_884);
  mesa3.add(nodes.Mesh6618_885);
  mesa3.add(nodes.Mesh6618_886);
  mesa3.add(nodes.Mesh6618_887);
  mesa3.add(nodes.Mesh6618_888);
  mesa3.add(nodes.Mesh6618_889);
  mesa3.add(nodes.Mesh6618_890);
  mesa3.add(nodes.Mesh6618_891);
  mesa3.add(nodes.Mesh6618_892);
  mesa3.add(nodes.Mesh6618_893);
  mesa3.add(nodes.Mesh6618_894);
  mesa3.add(nodes.Mesh6618_895);
  mesa3.add(nodes.Mesh6618_896);
  mesa3.add(nodes.Mesh6618_897);
  mesa3.add(nodes.Mesh6618_898);
  mesa3.add(nodes.Mesh6618_899);
  mesa3.add(nodes.Mesh6618_900);
  mesa3.add(nodes.Mesh6618_901);
  mesa3.add(nodes.Mesh6618_902);
  mesa3.add(nodes.Mesh6618_903);
  mesa3.add(nodes.Mesh6618_904);
  mesa3.add(nodes.Mesh6618_905);


  mesa4.add(nodes.Mesh6618_906);
  mesa4.add(nodes.Mesh6618_907);
  mesa4.add(nodes.Mesh6618_908);
  mesa4.add(nodes.Mesh6618_909);
  mesa4.add(nodes.Mesh6618_910);
  mesa4.add(nodes.Mesh6618_911);
  mesa4.add(nodes.Mesh6618_912);
  mesa4.add(nodes.Mesh6618_913);
  mesa4.add(nodes.Mesh6618_914);
  mesa4.add(nodes.Mesh6618_915);
  mesa4.add(nodes.Mesh6618_916);
  mesa4.add(nodes.Mesh6618_917);
  mesa4.add(nodes.Mesh6618_918);
  mesa4.add(nodes.Mesh6618_919);
  mesa4.add(nodes.Mesh6618_920);
  mesa4.add(nodes.Mesh6618_921);
  mesa4.add(nodes.Mesh6618_922);
  mesa4.add(nodes.Mesh6618_923);
  mesa4.add(nodes.Mesh6618_924);
  mesa4.add(nodes.Mesh6618_925);
  mesa4.add(nodes.Mesh6618_926);
  mesa4.add(nodes.Mesh6618_927);
  mesa4.add(nodes.Mesh6618_928);
  mesa4.add(nodes.Mesh6618_929);


  mesa5.add(nodes.Mesh6618_1038);
  mesa5.add(nodes.Mesh6618_1039);
  mesa5.add(nodes.Mesh6618_1040);
  mesa5.add(nodes.Mesh6618_1041);
  mesa5.add(nodes.Mesh6618_1042);
  mesa5.add(nodes.Mesh6618_1043);
  mesa5.add(nodes.Mesh6618_1044);
  mesa5.add(nodes.Mesh6618_1045);
  mesa5.add(nodes.Mesh6618_1046);
  mesa5.add(nodes.Mesh6618_1047);
  mesa5.add(nodes.Mesh6618_1048);
  mesa5.add(nodes.Mesh6618_1049);
  mesa5.add(nodes.Mesh6618_1050);
  mesa5.add(nodes.Mesh6618_1051);
  mesa5.add(nodes.Mesh6618_1052);
  mesa5.add(nodes.Mesh6618_1053);
  mesa5.add(nodes.Mesh6618_1054);
  mesa5.add(nodes.Mesh6618_1055);
  mesa5.add(nodes.Mesh6618_1056);
  mesa5.add(nodes.Mesh6618_1057);
  mesa5.add(nodes.Mesh6618_1058);
  mesa5.add(nodes.Mesh6618_1059);
  mesa5.add(nodes.Mesh6618_1060);
  mesa5.add(nodes.Mesh6618_1061);
  mesa5.add(nodes.Mesh6618_1062);
  mesa5.add(nodes.Mesh6618_1063);
  mesa5.add(nodes.Mesh6618_1064);
  mesa5.add(nodes.Mesh6618_1065);
  mesa5.add(nodes.Mesh6618_1066);
  mesa5.add(nodes.Mesh6618_1067);
  mesa5.add(nodes.Mesh6618_1068);
  mesa5.add(nodes.Mesh6618_1069);
  mesa5.add(nodes.Mesh6618_1070);
  mesa5.add(nodes.Mesh6618_1071);
  mesa5.add(nodes.Mesh6618_1072);
  mesa5.add(nodes.Mesh6618_1073);
  mesa5.add(nodes.Mesh6618_1074);
  mesa5.add(nodes.Mesh6618_1075);
  mesa5.add(nodes.Mesh6618_1076);
  mesa5.add(nodes.Mesh6618_1077);
  mesa5.add(nodes.Mesh6618_1078);
  mesa5.add(nodes.Mesh6618_1079);


  mesa6.add(nodes.Mesh6618_996);
  mesa6.add(nodes.Mesh6618_997);
  mesa6.add(nodes.Mesh6618_998);
  mesa6.add(nodes.Mesh6618_999);
  mesa6.add(nodes.Mesh6618_1000);
  mesa6.add(nodes.Mesh6618_1001);
  mesa6.add(nodes.Mesh6618_1002);
  mesa6.add(nodes.Mesh6618_1003);
  mesa6.add(nodes.Mesh6618_1004);
  mesa6.add(nodes.Mesh6618_1005);
  mesa6.add(nodes.Mesh6618_1006);
  mesa6.add(nodes.Mesh6618_1007);
  mesa6.add(nodes.Mesh6618_1008);
  mesa6.add(nodes.Mesh6618_1009);
  mesa6.add(nodes.Mesh6618_1010);
  mesa6.add(nodes.Mesh6618_1011);
  mesa6.add(nodes.Mesh6618_1012);
  mesa6.add(nodes.Mesh6618_1013);
  mesa6.add(nodes.Mesh6618_1014);
  mesa6.add(nodes.Mesh6618_1015);
  mesa6.add(nodes.Mesh6618_1016);
  mesa6.add(nodes.Mesh6618_1017);
  mesa6.add(nodes.Mesh6618_1018);
  mesa6.add(nodes.Mesh6618_1019);
  mesa6.add(nodes.Mesh6618_1020);
  mesa6.add(nodes.Mesh6618_1021);
  mesa6.add(nodes.Mesh6618_1022);
  mesa6.add(nodes.Mesh6618_1023);
  mesa6.add(nodes.Mesh6618_1024);
  mesa6.add(nodes.Mesh6618_1025);
  mesa6.add(nodes.Mesh6618_1026);
  mesa6.add(nodes.Mesh6618_1027);
  mesa6.add(nodes.Mesh6618_1028);
  mesa6.add(nodes.Mesh6618_1029);
  mesa6.add(nodes.Mesh6618_1030);
  mesa6.add(nodes.Mesh6618_1031);
  mesa6.add(nodes.Mesh6618_1032);
  mesa6.add(nodes.Mesh6618_1033);
  mesa6.add(nodes.Mesh6618_1034);
  mesa6.add(nodes.Mesh6618_1035);
  mesa6.add(nodes.Mesh6618_1036);
  mesa6.add(nodes.Mesh6618_1037);


  mesa7.add(nodes.Mesh6618_1080);
  mesa7.add(nodes.Mesh6618_1081);
  mesa7.add(nodes.Mesh6618_1082);
  mesa7.add(nodes.Mesh6618_1083);
  mesa7.add(nodes.Mesh6618_1084);
  mesa7.add(nodes.Mesh6618_1085);
  mesa7.add(nodes.Mesh6618_1086);
  mesa7.add(nodes.Mesh6618_1087);
  mesa7.add(nodes.Mesh6618_1088);
  mesa7.add(nodes.Mesh6618_1089);
  mesa7.add(nodes.Mesh6618_1090);
  mesa7.add(nodes.Mesh6618_1091);
  mesa7.add(nodes.Mesh6618_1092);
  mesa7.add(nodes.Mesh6618_1093);
  mesa7.add(nodes.Mesh6618_1094);
  mesa7.add(nodes.Mesh6618_1095);
  mesa7.add(nodes.Mesh6618_1096);
  mesa7.add(nodes.Mesh6618_1097);
  mesa7.add(nodes.Mesh6618_1098);
  mesa7.add(nodes.Mesh6618_1099);
  mesa7.add(nodes.Mesh6618_1100);
  mesa7.add(nodes.Mesh6618_1101);
  mesa7.add(nodes.Mesh6618_1102);
  mesa7.add(nodes.Mesh6618_1103);
  mesa7.add(nodes.Mesh6618_1104);
  mesa7.add(nodes.Mesh6618_1105);
  mesa7.add(nodes.Mesh6618_1106);
  mesa7.add(nodes.Mesh6618_1107);
  mesa7.add(nodes.Mesh6618_1108);
  mesa7.add(nodes.Mesh6618_1109);
  mesa7.add(nodes.Mesh6618_1110);
  mesa7.add(nodes.Mesh6618_1111);
  mesa7.add(nodes.Mesh6618_1112);
  mesa7.add(nodes.Mesh6618_1113);
  mesa7.add(nodes.Mesh6618_1114);
  mesa7.add(nodes.Mesh6618_1115);
  mesa7.add(nodes.Mesh6618_1116);
  mesa7.add(nodes.Mesh6618_1117);
  mesa7.add(nodes.Mesh6618_1118);
  mesa7.add(nodes.Mesh6618_1119);
  mesa7.add(nodes.Mesh6618_1120);
  mesa7.add(nodes.Mesh6618_1121);
  
  
  mesa8.add(nodes.Mesh6618_378);
  mesa8.add(nodes.Mesh6618_379);
  mesa8.add(nodes.Mesh6618_380);
  mesa8.add(nodes.Mesh6618_381);
  mesa8.add(nodes.Mesh6618_382);
  mesa8.add(nodes.Mesh6618_383);
  mesa8.add(nodes.Mesh6618_384);
  mesa8.add(nodes.Mesh6618_385);
  mesa8.add(nodes.Mesh6618_386);
  mesa8.add(nodes.Mesh6618_387);
  mesa8.add(nodes.Mesh6618_388);
  mesa8.add(nodes.Mesh6618_389);
  mesa8.add(nodes.Mesh6618_390);
  mesa8.add(nodes.Mesh6618_391);
  mesa8.add(nodes.Mesh6618_392);
  mesa8.add(nodes.Mesh6618_393);
  mesa8.add(nodes.Mesh6618_394);
  mesa8.add(nodes.Mesh6618_395);
  mesa8.add(nodes.Mesh6618_396);
  mesa8.add(nodes.Mesh6618_397);
  mesa8.add(nodes.Mesh6618_398);
  mesa8.add(nodes.Mesh6618_399);
  mesa8.add(nodes.Mesh6618_400);
  mesa8.add(nodes.Mesh6618_401);
  mesa8.add(nodes.Mesh6618_402);
  mesa8.add(nodes.Mesh6618_403);
  mesa8.add(nodes.Mesh6618_404);
  mesa8.add(nodes.Mesh6618_405);
  mesa8.add(nodes.Mesh6618_406);
  mesa8.add(nodes.Mesh6618_407);
  mesa8.add(nodes.Mesh6618_408);
  mesa8.add(nodes.Mesh6618_409);
  mesa8.add(nodes.Mesh6618_410);
  mesa8.add(nodes.Mesh6618_411);
  mesa8.add(nodes.Mesh6618_412);
  mesa8.add(nodes.Mesh6618_413);
  mesa8.add(nodes.Mesh6618_414);
  mesa8.add(nodes.Mesh6618_415);
  mesa8.add(nodes.Mesh6618_416);
  mesa8.add(nodes.Mesh6618_417);
  mesa8.add(nodes.Mesh6618_418);
  mesa8.add(nodes.Mesh6618_419);


  mesa9.add(nodes.Mesh6618_294);
  mesa9.add(nodes.Mesh6618_295);
  mesa9.add(nodes.Mesh6618_296);
  mesa9.add(nodes.Mesh6618_297);
  mesa9.add(nodes.Mesh6618_298);
  mesa9.add(nodes.Mesh6618_299);
  mesa9.add(nodes.Mesh6618_300);
  mesa9.add(nodes.Mesh6618_301);
  mesa9.add(nodes.Mesh6618_302);
  mesa9.add(nodes.Mesh6618_303);
  mesa9.add(nodes.Mesh6618_304);
  mesa9.add(nodes.Mesh6618_305);
  mesa9.add(nodes.Mesh6618_306);
  mesa9.add(nodes.Mesh6618_307);
  mesa9.add(nodes.Mesh6618_308);
  mesa9.add(nodes.Mesh6618_309);
  mesa9.add(nodes.Mesh6618_310);
  mesa9.add(nodes.Mesh6618_311);
  mesa9.add(nodes.Mesh6618_312);
  mesa9.add(nodes.Mesh6618_313);
  mesa9.add(nodes.Mesh6618_314);
  mesa9.add(nodes.Mesh6618_315);
  mesa9.add(nodes.Mesh6618_316);
  mesa9.add(nodes.Mesh6618_317);
  mesa9.add(nodes.Mesh6618_318);
  mesa9.add(nodes.Mesh6618_319);
  mesa9.add(nodes.Mesh6618_320);
  mesa9.add(nodes.Mesh6618_321);
  mesa9.add(nodes.Mesh6618_322);
  mesa9.add(nodes.Mesh6618_323);
  mesa9.add(nodes.Mesh6618_324);
  mesa9.add(nodes.Mesh6618_325);
  mesa9.add(nodes.Mesh6618_326);
  mesa9.add(nodes.Mesh6618_327);
  mesa9.add(nodes.Mesh6618_328);
  mesa9.add(nodes.Mesh6618_329);
  mesa9.add(nodes.Mesh6618_330);
  mesa9.add(nodes.Mesh6618_331);
  mesa9.add(nodes.Mesh6618_332);
  mesa9.add(nodes.Mesh6618_333);
  mesa9.add(nodes.Mesh6618_334);
  mesa9.add(nodes.Mesh6618_335);


  mesa10.add(nodes.Mesh6618_462);
  mesa10.add(nodes.Mesh6618_463);
  mesa10.add(nodes.Mesh6618_464);
  mesa10.add(nodes.Mesh6618_465);
  mesa10.add(nodes.Mesh6618_466);
  mesa10.add(nodes.Mesh6618_467);
  mesa10.add(nodes.Mesh6618_468);
  mesa10.add(nodes.Mesh6618_469);
  mesa10.add(nodes.Mesh6618_470);
  mesa10.add(nodes.Mesh6618_471);
  mesa10.add(nodes.Mesh6618_472);
  mesa10.add(nodes.Mesh6618_473);
  mesa10.add(nodes.Mesh6618_474);
  mesa10.add(nodes.Mesh6618_475);
  mesa10.add(nodes.Mesh6618_476);
  mesa10.add(nodes.Mesh6618_477);
  mesa10.add(nodes.Mesh6618_478);
  mesa10.add(nodes.Mesh6618_479);
  mesa10.add(nodes.Mesh6618_480);
  mesa10.add(nodes.Mesh6618_481);
  mesa10.add(nodes.Mesh6618_482);
  mesa10.add(nodes.Mesh6618_483);
  mesa10.add(nodes.Mesh6618_484);
  mesa10.add(nodes.Mesh6618_485);
  mesa10.add(nodes.Mesh6618_486);
  mesa10.add(nodes.Mesh6618_487);
  mesa10.add(nodes.Mesh6618_488);
  mesa10.add(nodes.Mesh6618_489);
  mesa10.add(nodes.Mesh6618_490);
  mesa10.add(nodes.Mesh6618_491);
  mesa10.add(nodes.Mesh6618_492);
  mesa10.add(nodes.Mesh6618_493);
  mesa10.add(nodes.Mesh6618_494);
  mesa10.add(nodes.Mesh6618_495);
  mesa10.add(nodes.Mesh6618_496);
  mesa10.add(nodes.Mesh6618_497);
  mesa10.add(nodes.Mesh6618_498);
  mesa10.add(nodes.Mesh6618_499);
  mesa10.add(nodes.Mesh6618_500);
  mesa10.add(nodes.Mesh6618_501);
  mesa10.add(nodes.Mesh6618_502);
  mesa10.add(nodes.Mesh6618_503);


  mesa11.add(nodes.Mesh6618_420);
  mesa11.add(nodes.Mesh6618_421);
  mesa11.add(nodes.Mesh6618_422);
  mesa11.add(nodes.Mesh6618_423);
  mesa11.add(nodes.Mesh6618_424);
  mesa11.add(nodes.Mesh6618_425);
  mesa11.add(nodes.Mesh6618_426);
  mesa11.add(nodes.Mesh6618_427);
  mesa11.add(nodes.Mesh6618_428);
  mesa11.add(nodes.Mesh6618_429);
  mesa11.add(nodes.Mesh6618_430);
  mesa11.add(nodes.Mesh6618_431);
  mesa11.add(nodes.Mesh6618_432);
  mesa11.add(nodes.Mesh6618_433);
  mesa11.add(nodes.Mesh6618_434);
  mesa11.add(nodes.Mesh6618_435);
  mesa11.add(nodes.Mesh6618_436);
  mesa11.add(nodes.Mesh6618_437);
  mesa11.add(nodes.Mesh6618_438);
  mesa11.add(nodes.Mesh6618_439);
  mesa11.add(nodes.Mesh6618_440);
  mesa11.add(nodes.Mesh6618_441);
  mesa11.add(nodes.Mesh6618_442);
  mesa11.add(nodes.Mesh6618_443);
  mesa11.add(nodes.Mesh6618_444);
  mesa11.add(nodes.Mesh6618_445);
  mesa11.add(nodes.Mesh6618_446);
  mesa11.add(nodes.Mesh6618_447);
  mesa11.add(nodes.Mesh6618_448);
  mesa11.add(nodes.Mesh6618_449);
  mesa11.add(nodes.Mesh6618_450);
  mesa11.add(nodes.Mesh6618_451);
  mesa11.add(nodes.Mesh6618_452);
  mesa11.add(nodes.Mesh6618_453);
  mesa11.add(nodes.Mesh6618_454);
  mesa11.add(nodes.Mesh6618_455);
  mesa11.add(nodes.Mesh6618_456);
  mesa11.add(nodes.Mesh6618_457);
  mesa11.add(nodes.Mesh6618_458);
  mesa11.add(nodes.Mesh6618_459);
  mesa11.add(nodes.Mesh6618_460);
  mesa11.add(nodes.Mesh6618_461);


  mesa12.add(nodes.Mesh6618_1164);
  mesa12.add(nodes.Mesh6618_1165);
  mesa12.add(nodes.Mesh6618_1166);
  mesa12.add(nodes.Mesh6618_1167);
  mesa12.add(nodes.Mesh6618_1168);
  mesa12.add(nodes.Mesh6618_1169);
  mesa12.add(nodes.Mesh6618_1170);
  mesa12.add(nodes.Mesh6618_1171);
  mesa12.add(nodes.Mesh6618_1172);
  mesa12.add(nodes.Mesh6618_1173);
  mesa12.add(nodes.Mesh6618_1174);
  mesa12.add(nodes.Mesh6618_1175);
  mesa12.add(nodes.Mesh6618_1176);
  mesa12.add(nodes.Mesh6618_1177);
  mesa12.add(nodes.Mesh6618_1178);
  mesa12.add(nodes.Mesh6618_1179);
  mesa12.add(nodes.Mesh6618_1180);
  mesa12.add(nodes.Mesh6618_1181);
  mesa12.add(nodes.Mesh6618_1182);
  mesa12.add(nodes.Mesh6618_1183);
  mesa12.add(nodes.Mesh6618_1184);
  mesa12.add(nodes.Mesh6618_1185);
  mesa12.add(nodes.Mesh6618_1186);
  mesa12.add(nodes.Mesh6618_1187);
  mesa12.add(nodes.Mesh6618_1188);
  mesa12.add(nodes.Mesh6618_1189);
  mesa12.add(nodes.Mesh6618_1190);
  mesa12.add(nodes.Mesh6618_1191);
  mesa12.add(nodes.Mesh6618_1192);
  mesa12.add(nodes.Mesh6618_1193);
  mesa12.add(nodes.Mesh6618_1194);
  mesa12.add(nodes.Mesh6618_1195);
  mesa12.add(nodes.Mesh6618_1196);
  mesa12.add(nodes.Mesh6618_1197);
  mesa12.add(nodes.Mesh6618_1198);
  mesa12.add(nodes.Mesh6618_1199);
  mesa12.add(nodes.Mesh6618_1200);
  mesa12.add(nodes.Mesh6618_1201);
  mesa12.add(nodes.Mesh6618_1202);
  mesa12.add(nodes.Mesh6618_1203);
  mesa12.add(nodes.Mesh6618_1204);
  mesa12.add(nodes.Mesh6618_1205);


  mesa13.add(nodes.Mesh6618_1206);
  mesa13.add(nodes.Mesh6618_1207);
  mesa13.add(nodes.Mesh6618_1208);
  mesa13.add(nodes.Mesh6618_1209);
  mesa13.add(nodes.Mesh6618_1210);
  mesa13.add(nodes.Mesh6618_1211);
  mesa13.add(nodes.Mesh6618_1212);
  mesa13.add(nodes.Mesh6618_1213);
  mesa13.add(nodes.Mesh6618_1214);
  mesa13.add(nodes.Mesh6618_1215);
  mesa13.add(nodes.Mesh6618_1216);
  mesa13.add(nodes.Mesh6618_1217);
  mesa13.add(nodes.Mesh6618_1218);
  mesa13.add(nodes.Mesh6618_1219);
  mesa13.add(nodes.Mesh6618_1220);
  mesa13.add(nodes.Mesh6618_1221);
  mesa13.add(nodes.Mesh6618_1222);
  mesa13.add(nodes.Mesh6618_1223);
  mesa13.add(nodes.Mesh6618_1224);
  mesa13.add(nodes.Mesh6618_1225);
  mesa13.add(nodes.Mesh6618_1226);
  mesa13.add(nodes.Mesh6618_1227);
  mesa13.add(nodes.Mesh6618_1228);
  mesa13.add(nodes.Mesh6618_1229);
  mesa13.add(nodes.Mesh6618_1230);
  mesa13.add(nodes.Mesh6618_1231);
  mesa13.add(nodes.Mesh6618_1232);
  mesa13.add(nodes.Mesh6618_1233);
  mesa13.add(nodes.Mesh6618_1234);
  mesa13.add(nodes.Mesh6618_1235);
  mesa13.add(nodes.Mesh6618_1236);
  mesa13.add(nodes.Mesh6618_1237);
  mesa13.add(nodes.Mesh6618_1238);
  mesa13.add(nodes.Mesh6618_1239);
  mesa13.add(nodes.Mesh6618_1240);
  mesa13.add(nodes.Mesh6618_1241);
  mesa13.add(nodes.Mesh6618_1242);
  mesa13.add(nodes.Mesh6618_1243);
  mesa13.add(nodes.Mesh6618_1244);
  mesa13.add(nodes.Mesh6618_1245);
  mesa13.add(nodes.Mesh6618_1246);
  mesa13.add(nodes.Mesh6618_1247);


  mesa14.add(nodes.Mesh6618_1122);
  mesa14.add(nodes.Mesh6618_1123);
  mesa14.add(nodes.Mesh6618_1124);
  mesa14.add(nodes.Mesh6618_1125);
  mesa14.add(nodes.Mesh6618_1126);
  mesa14.add(nodes.Mesh6618_1127);
  mesa14.add(nodes.Mesh6618_1128);
  mesa14.add(nodes.Mesh6618_1129);
  mesa14.add(nodes.Mesh6618_1130);
  mesa14.add(nodes.Mesh6618_1131);
  mesa14.add(nodes.Mesh6618_1132);
  mesa14.add(nodes.Mesh6618_1133);
  mesa14.add(nodes.Mesh6618_1134);
  mesa14.add(nodes.Mesh6618_1135);
  mesa14.add(nodes.Mesh6618_1136);
  mesa14.add(nodes.Mesh6618_1137);
  mesa14.add(nodes.Mesh6618_1138);
  mesa14.add(nodes.Mesh6618_1139);
  mesa14.add(nodes.Mesh6618_1140);
  mesa14.add(nodes.Mesh6618_1141);
  mesa14.add(nodes.Mesh6618_1142);
  mesa14.add(nodes.Mesh6618_1143);
  mesa14.add(nodes.Mesh6618_1144);
  mesa14.add(nodes.Mesh6618_1145);
  mesa14.add(nodes.Mesh6618_1146);
  mesa14.add(nodes.Mesh6618_1147);
  mesa14.add(nodes.Mesh6618_1148);
  mesa14.add(nodes.Mesh6618_1149);
  mesa14.add(nodes.Mesh6618_1150);
  mesa14.add(nodes.Mesh6618_1151);
  mesa14.add(nodes.Mesh6618_1152);
  mesa14.add(nodes.Mesh6618_1153);
  mesa14.add(nodes.Mesh6618_1154);
  mesa14.add(nodes.Mesh6618_1155);
  mesa14.add(nodes.Mesh6618_1156);
  mesa14.add(nodes.Mesh6618_1157);
  mesa14.add(nodes.Mesh6618_1158);
  mesa14.add(nodes.Mesh6618_1159);
  mesa14.add(nodes.Mesh6618_1160);
  mesa14.add(nodes.Mesh6618_1161);
  mesa14.add(nodes.Mesh6618_1162);
  mesa14.add(nodes.Mesh6618_1163);


  mesa15.add(nodes.Mesh6618_930);
  mesa15.add(nodes.Mesh6618_931);
  mesa15.add(nodes.Mesh6618_932);
  mesa15.add(nodes.Mesh6618_933);
  mesa15.add(nodes.Mesh6618_934);
  mesa15.add(nodes.Mesh6618_935);
  mesa15.add(nodes.Mesh6618_936);
  mesa15.add(nodes.Mesh6618_937);
  mesa15.add(nodes.Mesh6618_938);
  mesa15.add(nodes.Mesh6618_939);
  mesa15.add(nodes.Mesh6618_940);
  mesa15.add(nodes.Mesh6618_941);
  mesa15.add(nodes.Mesh6618_942);
  mesa15.add(nodes.Mesh6618_943);
  mesa15.add(nodes.Mesh6618_944);
  mesa15.add(nodes.Mesh6618_945);
  mesa15.add(nodes.Mesh6618_946);
  mesa15.add(nodes.Mesh6618_947);
  mesa15.add(nodes.Mesh6618_948);
  mesa15.add(nodes.Mesh6618_949);
  mesa15.add(nodes.Mesh6618_950);
  mesa15.add(nodes.Mesh6618_951);
  mesa15.add(nodes.Mesh6618_952);
  mesa15.add(nodes.Mesh6618_953);
  mesa15.add(nodes.Mesh6618_954);
  mesa15.add(nodes.Mesh6618_955);
  mesa15.add(nodes.Mesh6618_956);
  mesa15.add(nodes.Mesh6618_957);
  mesa15.add(nodes.Mesh6618_958);
  mesa15.add(nodes.Mesh6618_959);
  mesa15.add(nodes.Mesh6618_960);
  mesa15.add(nodes.Mesh6618_961);
  mesa15.add(nodes.Mesh6618_962);
  mesa15.add(nodes.Mesh6618_963);
  mesa15.add(nodes.Mesh6618_964);
  mesa15.add(nodes.Mesh6618_965);
  mesa15.add(nodes.Mesh6618_966);
  mesa15.add(nodes.Mesh6618_967);
  mesa15.add(nodes.Mesh6618_968);
  mesa15.add(nodes.Mesh6618_969);
  mesa15.add(nodes.Mesh6618_970);
  mesa15.add(nodes.Mesh6618_971);


  mesa16.add(nodes.Mesh6618_126);
  mesa16.add(nodes.Mesh6618_127);
  mesa16.add(nodes.Mesh6618_128);
  mesa16.add(nodes.Mesh6618_129);
  mesa16.add(nodes.Mesh6618_130);
  mesa16.add(nodes.Mesh6618_131);
  mesa16.add(nodes.Mesh6618_132);
  mesa16.add(nodes.Mesh6618_133);
  mesa16.add(nodes.Mesh6618_134);
  mesa16.add(nodes.Mesh6618_135);
  mesa16.add(nodes.Mesh6618_136);
  mesa16.add(nodes.Mesh6618_137);
  mesa16.add(nodes.Mesh6618_138);
  mesa16.add(nodes.Mesh6618_139);
  mesa16.add(nodes.Mesh6618_140);
  mesa16.add(nodes.Mesh6618_141);
  mesa16.add(nodes.Mesh6618_142);
  mesa16.add(nodes.Mesh6618_143);
  mesa16.add(nodes.Mesh6618_144);
  mesa16.add(nodes.Mesh6618_145);
  mesa16.add(nodes.Mesh6618_146);
  mesa16.add(nodes.Mesh6618_147);
  mesa16.add(nodes.Mesh6618_148);
  mesa16.add(nodes.Mesh6618_149);
  mesa16.add(nodes.Mesh6618_150);
  mesa16.add(nodes.Mesh6618_151);
  mesa16.add(nodes.Mesh6618_152);
  mesa16.add(nodes.Mesh6618_153);
  mesa16.add(nodes.Mesh6618_154);
  mesa16.add(nodes.Mesh6618_155);
  mesa16.add(nodes.Mesh6618_156);
  mesa16.add(nodes.Mesh6618_157);
  mesa16.add(nodes.Mesh6618_158);
  mesa16.add(nodes.Mesh6618_159);
  mesa16.add(nodes.Mesh6618_160);
  mesa16.add(nodes.Mesh6618_161);
  mesa16.add(nodes.Mesh6618_162);
  mesa16.add(nodes.Mesh6618_163);
  mesa16.add(nodes.Mesh6618_164);
  mesa16.add(nodes.Mesh6618_165);
  mesa16.add(nodes.Mesh6618_166);
  mesa16.add(nodes.Mesh6618_167);


  mesa17.add(nodes.Mesh6618_210);
  mesa17.add(nodes.Mesh6618_211);
  mesa17.add(nodes.Mesh6618_212);
  mesa17.add(nodes.Mesh6618_213);
  mesa17.add(nodes.Mesh6618_214);
  mesa17.add(nodes.Mesh6618_215);
  mesa17.add(nodes.Mesh6618_216);
  mesa17.add(nodes.Mesh6618_217);
  mesa17.add(nodes.Mesh6618_218);
  mesa17.add(nodes.Mesh6618_219);
  mesa17.add(nodes.Mesh6618_220);
  mesa17.add(nodes.Mesh6618_221);
  mesa17.add(nodes.Mesh6618_222);
  mesa17.add(nodes.Mesh6618_223);
  mesa17.add(nodes.Mesh6618_224);
  mesa17.add(nodes.Mesh6618_225);
  mesa17.add(nodes.Mesh6618_226);
  mesa17.add(nodes.Mesh6618_227);
  mesa17.add(nodes.Mesh6618_228);
  mesa17.add(nodes.Mesh6618_229);
  mesa17.add(nodes.Mesh6618_230);
  mesa17.add(nodes.Mesh6618_231);
  mesa17.add(nodes.Mesh6618_232);
  mesa17.add(nodes.Mesh6618_233);
  mesa17.add(nodes.Mesh6618_234);
  mesa17.add(nodes.Mesh6618_235);
  mesa17.add(nodes.Mesh6618_236);
  mesa17.add(nodes.Mesh6618_237);
  mesa17.add(nodes.Mesh6618_238);
  mesa17.add(nodes.Mesh6618_239);
  mesa17.add(nodes.Mesh6618_240);
  mesa17.add(nodes.Mesh6618_241);
  mesa17.add(nodes.Mesh6618_242);
  mesa17.add(nodes.Mesh6618_243);
  mesa17.add(nodes.Mesh6618_244);
  mesa17.add(nodes.Mesh6618_245);
  mesa17.add(nodes.Mesh6618_246);
  mesa17.add(nodes.Mesh6618_247);
  mesa17.add(nodes.Mesh6618_248);
  mesa17.add(nodes.Mesh6618_249);
  mesa17.add(nodes.Mesh6618_250);
  mesa17.add(nodes.Mesh6618_251);
  

  mesa18.add(nodes.Mesh6618_84);
  mesa18.add(nodes.Mesh6618_85);
  mesa18.add(nodes.Mesh6618_86);
  mesa18.add(nodes.Mesh6618_87);
  mesa18.add(nodes.Mesh6618_88);
  mesa18.add(nodes.Mesh6618_89);
  mesa18.add(nodes.Mesh6618_90);
  mesa18.add(nodes.Mesh6618_91);
  mesa18.add(nodes.Mesh6618_92);
  mesa18.add(nodes.Mesh6618_93);
  mesa18.add(nodes.Mesh6618_94);
  mesa18.add(nodes.Mesh6618_95);
  mesa18.add(nodes.Mesh6618_96);
  mesa18.add(nodes.Mesh6618_97);
  mesa18.add(nodes.Mesh6618_98);
  mesa18.add(nodes.Mesh6618_99);
  mesa18.add(nodes.Mesh6618_100);
  mesa18.add(nodes.Mesh6618_101);
  mesa18.add(nodes.Mesh6618_102);
  mesa18.add(nodes.Mesh6618_103);
  mesa18.add(nodes.Mesh6618_104);
  mesa18.add(nodes.Mesh6618_105);
  mesa18.add(nodes.Mesh6618_106);
  mesa18.add(nodes.Mesh6618_107);
  mesa18.add(nodes.Mesh6618_108);
  mesa18.add(nodes.Mesh6618_109);
  mesa18.add(nodes.Mesh6618_110);
  mesa18.add(nodes.Mesh6618_111);
  mesa18.add(nodes.Mesh6618_112);
  mesa18.add(nodes.Mesh6618_113);
  mesa18.add(nodes.Mesh6618_114);
  mesa18.add(nodes.Mesh6618_115);
  mesa18.add(nodes.Mesh6618_116);
  mesa18.add(nodes.Mesh6618_117);
  mesa18.add(nodes.Mesh6618_118);
  mesa18.add(nodes.Mesh6618_119);
  mesa18.add(nodes.Mesh6618_120);
  mesa18.add(nodes.Mesh6618_121);
  mesa18.add(nodes.Mesh6618_122);
  mesa18.add(nodes.Mesh6618_123);
  mesa18.add(nodes.Mesh6618_124);
  mesa18.add(nodes.Mesh6618_125);


  mesa19.add(nodes.Mesh6618_168);
  mesa19.add(nodes.Mesh6618_169);
  mesa19.add(nodes.Mesh6618_170);
  mesa19.add(nodes.Mesh6618_171);
  mesa19.add(nodes.Mesh6618_172);
  mesa19.add(nodes.Mesh6618_173);
  mesa19.add(nodes.Mesh6618_174);
  mesa19.add(nodes.Mesh6618_175);
  mesa19.add(nodes.Mesh6618_176);
  mesa19.add(nodes.Mesh6618_177);
  mesa19.add(nodes.Mesh6618_178);
  mesa19.add(nodes.Mesh6618_179);
  mesa19.add(nodes.Mesh6618_180);
  mesa19.add(nodes.Mesh6618_181);
  mesa19.add(nodes.Mesh6618_182);
  mesa19.add(nodes.Mesh6618_183);
  mesa19.add(nodes.Mesh6618_184);
  mesa19.add(nodes.Mesh6618_185);
  mesa19.add(nodes.Mesh6618_186);
  mesa19.add(nodes.Mesh6618_187);
  mesa19.add(nodes.Mesh6618_188);
  mesa19.add(nodes.Mesh6618_189);
  mesa19.add(nodes.Mesh6618_190);
  mesa19.add(nodes.Mesh6618_191);
  mesa19.add(nodes.Mesh6618_192);
  mesa19.add(nodes.Mesh6618_193);
  mesa19.add(nodes.Mesh6618_194);
  mesa19.add(nodes.Mesh6618_195);
  mesa19.add(nodes.Mesh6618_196);
  mesa19.add(nodes.Mesh6618_197);
  mesa19.add(nodes.Mesh6618_198);
  mesa19.add(nodes.Mesh6618_199);
  mesa19.add(nodes.Mesh6618_200);
  mesa19.add(nodes.Mesh6618_201);
  mesa19.add(nodes.Mesh6618_202);
  mesa19.add(nodes.Mesh6618_203);
  mesa19.add(nodes.Mesh6618_204);
  mesa19.add(nodes.Mesh6618_205);
  mesa19.add(nodes.Mesh6618_206);
  mesa19.add(nodes.Mesh6618_207);
  mesa19.add(nodes.Mesh6618_208);
  mesa19.add(nodes.Mesh6618_209);


  mesa20.add(nodes.Mesh6618_252);
  mesa20.add(nodes.Mesh6618_253);
  mesa20.add(nodes.Mesh6618_254);
  mesa20.add(nodes.Mesh6618_255);
  mesa20.add(nodes.Mesh6618_256);
  mesa20.add(nodes.Mesh6618_257);
  mesa20.add(nodes.Mesh6618_258);
  mesa20.add(nodes.Mesh6618_259);
  mesa20.add(nodes.Mesh6618_260);
  mesa20.add(nodes.Mesh6618_261);
  mesa20.add(nodes.Mesh6618_262);
  mesa20.add(nodes.Mesh6618_263);
  mesa20.add(nodes.Mesh6618_264);
  mesa20.add(nodes.Mesh6618_265);
  mesa20.add(nodes.Mesh6618_266);
  mesa20.add(nodes.Mesh6618_267);
  mesa20.add(nodes.Mesh6618_268);
  mesa20.add(nodes.Mesh6618_269);
  mesa20.add(nodes.Mesh6618_270);
  mesa20.add(nodes.Mesh6618_271);
  mesa20.add(nodes.Mesh6618_272);
  mesa20.add(nodes.Mesh6618_273);
  mesa20.add(nodes.Mesh6618_274);
  mesa20.add(nodes.Mesh6618_275);
  mesa20.add(nodes.Mesh6618_276);
  mesa20.add(nodes.Mesh6618_277);
  mesa20.add(nodes.Mesh6618_278);
  mesa20.add(nodes.Mesh6618_279);
  mesa20.add(nodes.Mesh6618_280);
  mesa20.add(nodes.Mesh6618_281);
  mesa20.add(nodes.Mesh6618_282);
  mesa20.add(nodes.Mesh6618_283);
  mesa20.add(nodes.Mesh6618_284);
  mesa20.add(nodes.Mesh6618_285);
  mesa20.add(nodes.Mesh6618_286);
  mesa20.add(nodes.Mesh6618_287);
  mesa20.add(nodes.Mesh6618_288);
  mesa20.add(nodes.Mesh6618_289);
  mesa20.add(nodes.Mesh6618_290);
  mesa20.add(nodes.Mesh6618_291);
  mesa20.add(nodes.Mesh6618_292);
  mesa20.add(nodes.Mesh6618_293);


  mesa21.add(nodes.Mesh6618_336);
  mesa21.add(nodes.Mesh6618_337);
  mesa21.add(nodes.Mesh6618_338);
  mesa21.add(nodes.Mesh6618_339);
  mesa21.add(nodes.Mesh6618_340);
  mesa21.add(nodes.Mesh6618_341);
  mesa21.add(nodes.Mesh6618_342);
  mesa21.add(nodes.Mesh6618_343);
  mesa21.add(nodes.Mesh6618_344);
  mesa21.add(nodes.Mesh6618_345);
  mesa21.add(nodes.Mesh6618_346);
  mesa21.add(nodes.Mesh6618_347);
  mesa21.add(nodes.Mesh6618_348);
  mesa21.add(nodes.Mesh6618_349);
  mesa21.add(nodes.Mesh6618_350);
  mesa21.add(nodes.Mesh6618_351);
  mesa21.add(nodes.Mesh6618_352);
  mesa21.add(nodes.Mesh6618_353);
  mesa21.add(nodes.Mesh6618_354);
  mesa21.add(nodes.Mesh6618_355);
  mesa21.add(nodes.Mesh6618_356);
  mesa21.add(nodes.Mesh6618_357);
  mesa21.add(nodes.Mesh6618_358);
  mesa21.add(nodes.Mesh6618_359);
  mesa21.add(nodes.Mesh6618_360);
  mesa21.add(nodes.Mesh6618_361);
  mesa21.add(nodes.Mesh6618_362);
  mesa21.add(nodes.Mesh6618_363);
  mesa21.add(nodes.Mesh6618_364);
  mesa21.add(nodes.Mesh6618_365);
  mesa21.add(nodes.Mesh6618_366);
  mesa21.add(nodes.Mesh6618_367);
  mesa21.add(nodes.Mesh6618_368);
  mesa21.add(nodes.Mesh6618_369);
  mesa21.add(nodes.Mesh6618_370);
  mesa21.add(nodes.Mesh6618_371);
  mesa21.add(nodes.Mesh6618_372);
  mesa21.add(nodes.Mesh6618_373);
  mesa21.add(nodes.Mesh6618_374);
  mesa21.add(nodes.Mesh6618_375);
  mesa21.add(nodes.Mesh6618_376);
  mesa21.add(nodes.Mesh6618_377);


  mesa22.add(nodes.Mesh6618_504);
  mesa22.add(nodes.Mesh6618_505);
  mesa22.add(nodes.Mesh6618_506);
  mesa22.add(nodes.Mesh6618_507);
  mesa22.add(nodes.Mesh6618_508);
  mesa22.add(nodes.Mesh6618_509);
  mesa22.add(nodes.Mesh6618_510);
  mesa22.add(nodes.Mesh6618_511);
  mesa22.add(nodes.Mesh6618_512);
  mesa22.add(nodes.Mesh6618_513);
  mesa22.add(nodes.Mesh6618_514);
  mesa22.add(nodes.Mesh6618_515);
  mesa22.add(nodes.Mesh6618_516);
  mesa22.add(nodes.Mesh6618_517);
  mesa22.add(nodes.Mesh6618_518);
  mesa22.add(nodes.Mesh6618_519);
  mesa22.add(nodes.Mesh6618_520);
  mesa22.add(nodes.Mesh6618_521);
  mesa22.add(nodes.Mesh6618_522);
  mesa22.add(nodes.Mesh6618_523);
  mesa22.add(nodes.Mesh6618_524);
  mesa22.add(nodes.Mesh6618_525);
  mesa22.add(nodes.Mesh6618_526);
  mesa22.add(nodes.Mesh6618_527);
  mesa22.add(nodes.Mesh6618_528);
  mesa22.add(nodes.Mesh6618_529);
  mesa22.add(nodes.Mesh6618_530);
  mesa22.add(nodes.Mesh6618_531);
  mesa22.add(nodes.Mesh6618_532);
  mesa22.add(nodes.Mesh6618_533);
  mesa22.add(nodes.Mesh6618_534);
  mesa22.add(nodes.Mesh6618_535);
  mesa22.add(nodes.Mesh6618_536);
  mesa22.add(nodes.Mesh6618_537);
  mesa22.add(nodes.Mesh6618_538);
  mesa22.add(nodes.Mesh6618_539);
  mesa22.add(nodes.Mesh6618_540);
  mesa22.add(nodes.Mesh6618_541);
  mesa22.add(nodes.Mesh6618_542);
  mesa22.add(nodes.Mesh6618_543);
  mesa22.add(nodes.Mesh6618_544);
  mesa22.add(nodes.Mesh6618_545);


  mesa23.add(nodes.Mesh6618_546);
  mesa23.add(nodes.Mesh6618_547);
  mesa23.add(nodes.Mesh6618_548);
  mesa23.add(nodes.Mesh6618_549);
  mesa23.add(nodes.Mesh6618_550);
  mesa23.add(nodes.Mesh6618_551);
  mesa23.add(nodes.Mesh6618_552);
  mesa23.add(nodes.Mesh6618_553);
  mesa23.add(nodes.Mesh6618_554);
  mesa23.add(nodes.Mesh6618_555);
  mesa23.add(nodes.Mesh6618_556);
  mesa23.add(nodes.Mesh6618_557);
  mesa23.add(nodes.Mesh6618_558);
  mesa23.add(nodes.Mesh6618_559);
  mesa23.add(nodes.Mesh6618_560);
  mesa23.add(nodes.Mesh6618_561);
  mesa23.add(nodes.Mesh6618_562);
  mesa23.add(nodes.Mesh6618_563);
  mesa23.add(nodes.Mesh6618_564);
  mesa23.add(nodes.Mesh6618_565);
  mesa23.add(nodes.Mesh6618_566);
  mesa23.add(nodes.Mesh6618_567);
  mesa23.add(nodes.Mesh6618_568);
  mesa23.add(nodes.Mesh6618_569);
  mesa23.add(nodes.Mesh6618_570);
  mesa23.add(nodes.Mesh6618_571);
  mesa23.add(nodes.Mesh6618_572);
  mesa23.add(nodes.Mesh6618_573);
  mesa23.add(nodes.Mesh6618_574);
  mesa23.add(nodes.Mesh6618_575);
  mesa23.add(nodes.Mesh6618_576);
  mesa23.add(nodes.Mesh6618_577);
  mesa23.add(nodes.Mesh6618_578);
  mesa23.add(nodes.Mesh6618_579);
  mesa23.add(nodes.Mesh6618_580);
  mesa23.add(nodes.Mesh6618_581);
  mesa23.add(nodes.Mesh6618_582);
  mesa23.add(nodes.Mesh6618_583);
  mesa23.add(nodes.Mesh6618_584);
  mesa23.add(nodes.Mesh6618_585);
  mesa23.add(nodes.Mesh6618_586);
  mesa23.add(nodes.Mesh6618_587);


  mesa24.add(nodes.Mesh6618_588)
  mesa24.add(nodes.Mesh6618_589);
  mesa24.add(nodes.Mesh6618_590);
  mesa24.add(nodes.Mesh6618_591);
  mesa24.add(nodes.Mesh6618_592);
  mesa24.add(nodes.Mesh6618_593);
  mesa24.add(nodes.Mesh6618_594);
  mesa24.add(nodes.Mesh6618_595);
  mesa24.add(nodes.Mesh6618_596);
  mesa24.add(nodes.Mesh6618_597);
  mesa24.add(nodes.Mesh6618_598);
  mesa24.add(nodes.Mesh6618_599);
  mesa24.add(nodes.Mesh6618_600);
  mesa24.add(nodes.Mesh6618_601);
  mesa24.add(nodes.Mesh6618_602);
  mesa24.add(nodes.Mesh6618_603);
  mesa24.add(nodes.Mesh6618_604);
  mesa24.add(nodes.Mesh6618_605);
  mesa24.add(nodes.Mesh6618_606);
  mesa24.add(nodes.Mesh6618_607);
  mesa24.add(nodes.Mesh6618_608);
  mesa24.add(nodes.Mesh6618_609);
  mesa24.add(nodes.Mesh6618_610);
  mesa24.add(nodes.Mesh6618_611);
  mesa24.add(nodes.Mesh6618_612);
  mesa24.add(nodes.Mesh6618_613);
  mesa24.add(nodes.Mesh6618_614);
  mesa24.add(nodes.Mesh6618_615);
  mesa24.add(nodes.Mesh6618_616);
  mesa24.add(nodes.Mesh6618_617);
  mesa24.add(nodes.Mesh6618_618);
  mesa24.add(nodes.Mesh6618_619);
  mesa24.add(nodes.Mesh6618_620);
  mesa24.add(nodes.Mesh6618_621);
  mesa24.add(nodes.Mesh6618_622);
  mesa24.add(nodes.Mesh6618_623);
  mesa24.add(nodes.Mesh6618_624);
  mesa24.add(nodes.Mesh6618_625);
  mesa24.add(nodes.Mesh6618_626);
  mesa24.add(nodes.Mesh6618_627);
  mesa24.add(nodes.Mesh6618_628);
  mesa24.add(nodes.Mesh6618_629);


  mesa25.add(nodes.Mesh6618_630);
  mesa25.add(nodes.Mesh6618_631);
  mesa25.add(nodes.Mesh6618_632);
  mesa25.add(nodes.Mesh6618_633);
  mesa25.add(nodes.Mesh6618_634);
  mesa25.add(nodes.Mesh6618_635);
  mesa25.add(nodes.Mesh6618_636);
  mesa25.add(nodes.Mesh6618_637);
  mesa25.add(nodes.Mesh6618_638);
  mesa25.add(nodes.Mesh6618_639);
  mesa25.add(nodes.Mesh6618_640);
  mesa25.add(nodes.Mesh6618_641);
  mesa25.add(nodes.Mesh6618_642);
  mesa25.add(nodes.Mesh6618_643);
  mesa25.add(nodes.Mesh6618_644);
  mesa25.add(nodes.Mesh6618_645);
  mesa25.add(nodes.Mesh6618_646);
  mesa25.add(nodes.Mesh6618_647);
  mesa25.add(nodes.Mesh6618_648);
  mesa25.add(nodes.Mesh6618_649);
  mesa25.add(nodes.Mesh6618_650);
  mesa25.add(nodes.Mesh6618_651);
  mesa25.add(nodes.Mesh6618_652);
  mesa25.add(nodes.Mesh6618_653);
  mesa25.add(nodes.Mesh6618_654);
  mesa25.add(nodes.Mesh6618_655);
  mesa25.add(nodes.Mesh6618_656);
  mesa25.add(nodes.Mesh6618_657);
  mesa25.add(nodes.Mesh6618_658);
  mesa25.add(nodes.Mesh6618_659);
  mesa25.add(nodes.Mesh6618_660);
  mesa25.add(nodes.Mesh6618_661);
  mesa25.add(nodes.Mesh6618_662);
  mesa25.add(nodes.Mesh6618_663);
  mesa25.add(nodes.Mesh6618_664);
  mesa25.add(nodes.Mesh6618_665);
  mesa25.add(nodes.Mesh6618_666);
  mesa25.add(nodes.Mesh6618_667);
  mesa25.add(nodes.Mesh6618_668);
  mesa25.add(nodes.Mesh6618_669);
  mesa25.add(nodes.Mesh6618_670);
  mesa25.add(nodes.Mesh6618_671);


  mesa26.add(nodes.Mesh6618_672);
  mesa26.add(nodes.Mesh6618_673);
  mesa26.add(nodes.Mesh6618_674);
  mesa26.add(nodes.Mesh6618_675);
  mesa26.add(nodes.Mesh6618_676);
  mesa26.add(nodes.Mesh6618_677);
  mesa26.add(nodes.Mesh6618_678);
  mesa26.add(nodes.Mesh6618_679);
  mesa26.add(nodes.Mesh6618_680);
  mesa26.add(nodes.Mesh6618_681);
  mesa26.add(nodes.Mesh6618_682);
  mesa26.add(nodes.Mesh6618_683);
  mesa26.add(nodes.Mesh6618_684);
  mesa26.add(nodes.Mesh6618_685);
  mesa26.add(nodes.Mesh6618_686);
  mesa26.add(nodes.Mesh6618_687);
  mesa26.add(nodes.Mesh6618_688);
  mesa26.add(nodes.Mesh6618_689);
  mesa26.add(nodes.Mesh6618_690);
  mesa26.add(nodes.Mesh6618_691);
  mesa26.add(nodes.Mesh6618_692);
  mesa26.add(nodes.Mesh6618_693);
  mesa26.add(nodes.Mesh6618_694);
  mesa26.add(nodes.Mesh6618_695);
  mesa26.add(nodes.Mesh6618_696);
  mesa26.add(nodes.Mesh6618_697);
  mesa26.add(nodes.Mesh6618_698);
  mesa26.add(nodes.Mesh6618_699);
  mesa26.add(nodes.Mesh6618_700);
  mesa26.add(nodes.Mesh6618_701);
  mesa26.add(nodes.Mesh6618_702);
  mesa26.add(nodes.Mesh6618_703);
  mesa26.add(nodes.Mesh6618_704);
  mesa26.add(nodes.Mesh6618_705);
  mesa26.add(nodes.Mesh6618_706);
  mesa26.add(nodes.Mesh6618_707);
  mesa26.add(nodes.Mesh6618_708);
  mesa26.add(nodes.Mesh6618_709);
  mesa26.add(nodes.Mesh6618_710);
  mesa26.add(nodes.Mesh6618_711);
  mesa26.add(nodes.Mesh6618_712);
  mesa26.add(nodes.Mesh6618_713);


  mesa27.add(nodes.Mesh6618_735);
  mesa27.add(nodes.Mesh6618_736);
  mesa27.add(nodes.Mesh6618_737);
  mesa27.add(nodes.Mesh6618_738);
  mesa27.add(nodes.Mesh6618_739);
  mesa27.add(nodes.Mesh6618_740);
  mesa27.add(nodes.Mesh6618_741);
  mesa27.add(nodes.Mesh6618_742);
  mesa27.add(nodes.Mesh6618_743);
  mesa27.add(nodes.Mesh6618_744);
  mesa27.add(nodes.Mesh6618_745);
  mesa27.add(nodes.Mesh6618_746);
  mesa27.add(nodes.Mesh6618_747);
  mesa27.add(nodes.Mesh6618_748);
  mesa27.add(nodes.Mesh6618_749);
  mesa27.add(nodes.Mesh6618_750);
  mesa27.add(nodes.Mesh6618_751);
  mesa27.add(nodes.Mesh6618_752);
  mesa27.add(nodes.Mesh6618_753);
  mesa27.add(nodes.Mesh6618_754);
  mesa27.add(nodes.Mesh6618_755);


  mesa28.add(nodes.Mesh6618_714);
  mesa28.add(nodes.Mesh6618_715);
  mesa28.add(nodes.Mesh6618_716);
  mesa28.add(nodes.Mesh6618_717);
  mesa28.add(nodes.Mesh6618_718);
  mesa28.add(nodes.Mesh6618_719);
  mesa28.add(nodes.Mesh6618_720);
  mesa28.add(nodes.Mesh6618_721);
  mesa28.add(nodes.Mesh6618_722);
  mesa28.add(nodes.Mesh6618_723);
  mesa28.add(nodes.Mesh6618_724);
  mesa28.add(nodes.Mesh6618_725);
  mesa28.add(nodes.Mesh6618_726);
  mesa28.add(nodes.Mesh6618_727);
  mesa28.add(nodes.Mesh6618_728);
  mesa28.add(nodes.Mesh6618_729);
  mesa28.add(nodes.Mesh6618_730);
  mesa28.add(nodes.Mesh6618_731);
  mesa28.add(nodes.Mesh6618_732);
  mesa28.add(nodes.Mesh6618_733);
  mesa28.add(nodes.Mesh6618_734);


  mesa29.add(nodes.Mesh6618_756);
  mesa29.add(nodes.Mesh6618_757);
  mesa29.add(nodes.Mesh6618_758);
  mesa29.add(nodes.Mesh6618_759);
  mesa29.add(nodes.Mesh6618_760);
  mesa29.add(nodes.Mesh6618_761);
  mesa29.add(nodes.Mesh6618_762);
  mesa29.add(nodes.Mesh6618_763);
  mesa29.add(nodes.Mesh6618_764);
  mesa29.add(nodes.Mesh6618_765);
  mesa29.add(nodes.Mesh6618_766);
  mesa29.add(nodes.Mesh6618_767);
  mesa29.add(nodes.Mesh6618_768);
  mesa29.add(nodes.Mesh6618_769);
  mesa29.add(nodes.Mesh6618_770);
  mesa29.add(nodes.Mesh6618_771);
  mesa29.add(nodes.Mesh6618_772);
  mesa29.add(nodes.Mesh6618_773);
  mesa29.add(nodes.Mesh6618_774);
  mesa29.add(nodes.Mesh6618_775);
  mesa29.add(nodes.Mesh6618_776);


  mesa30.add(nodes.Mesh6618_777);
  mesa30.add(nodes.Mesh6618_778);
  mesa30.add(nodes.Mesh6618_779);
  mesa30.add(nodes.Mesh6618_780);
  mesa30.add(nodes.Mesh6618_781);
  mesa30.add(nodes.Mesh6618_782);
  mesa30.add(nodes.Mesh6618_783);
  mesa30.add(nodes.Mesh6618_784);
  mesa30.add(nodes.Mesh6618_785);
  mesa30.add(nodes.Mesh6618_786);
  mesa30.add(nodes.Mesh6618_787);
  mesa30.add(nodes.Mesh6618_788);
  mesa30.add(nodes.Mesh6618_789);
  mesa30.add(nodes.Mesh6618_790);
  mesa30.add(nodes.Mesh6618_791);
  mesa30.add(nodes.Mesh6618_792);
  mesa30.add(nodes.Mesh6618_793);
  mesa30.add(nodes.Mesh6618_794);
  mesa30.add(nodes.Mesh6618_795);
  mesa30.add(nodes.Mesh6618_796);
  mesa30.add(nodes.Mesh6618_797);


  mesa31.add(nodes.Mesh6618_861);
  mesa31.add(nodes.Mesh6618_862);
  mesa31.add(nodes.Mesh6618_863);
  mesa31.add(nodes.Mesh6618_864);
  mesa31.add(nodes.Mesh6618_865);
  mesa31.add(nodes.Mesh6618_866);
  mesa31.add(nodes.Mesh6618_867);
  mesa31.add(nodes.Mesh6618_868);
  mesa31.add(nodes.Mesh6618_869);
  mesa31.add(nodes.Mesh6618_870);
  mesa31.add(nodes.Mesh6618_871);
  mesa31.add(nodes.Mesh6618_872);
  mesa31.add(nodes.Mesh6618_873);
  mesa31.add(nodes.Mesh6618_874);
  mesa31.add(nodes.Mesh6618_875);
  mesa31.add(nodes.Mesh6618_876);
  mesa31.add(nodes.Mesh6618_877);
  mesa31.add(nodes.Mesh6618_878);
  mesa31.add(nodes.Mesh6618_879);
  mesa31.add(nodes.Mesh6618_880);
  mesa31.add(nodes.Mesh6618_881);


  mesa32.add(nodes.Mesh6618_840);
  mesa32.add(nodes.Mesh6618_841);
  mesa32.add(nodes.Mesh6618_842);
  mesa32.add(nodes.Mesh6618_843);
  mesa32.add(nodes.Mesh6618_844);
  mesa32.add(nodes.Mesh6618_845);
  mesa32.add(nodes.Mesh6618_846);
  mesa32.add(nodes.Mesh6618_847);
  mesa32.add(nodes.Mesh6618_848);
  mesa32.add(nodes.Mesh6618_849);
  mesa32.add(nodes.Mesh6618_850);
  mesa32.add(nodes.Mesh6618_851);
  mesa32.add(nodes.Mesh6618_852);
  mesa32.add(nodes.Mesh6618_853);
  mesa32.add(nodes.Mesh6618_854);
  mesa32.add(nodes.Mesh6618_855);
  mesa32.add(nodes.Mesh6618_856);
  mesa32.add(nodes.Mesh6618_857);
  mesa32.add(nodes.Mesh6618_858);
  mesa32.add(nodes.Mesh6618_859);
  mesa32.add(nodes.Mesh6618_860);


  mesa33.add(nodes.Mesh6618_1293);
  mesa33.add(nodes.Mesh6618_1294);
  mesa33.add(nodes.Mesh6618_1295);
  mesa33.add(nodes.Mesh6618_1296);
  mesa33.add(nodes.Mesh6618_1297);
  mesa33.add(nodes.Mesh6618_1298);
  mesa33.add(nodes.Mesh6618_1299);
  mesa33.add(nodes.Mesh6618_1300);
  mesa33.add(nodes.Mesh6618_1301);
  mesa33.add(nodes.Mesh6618_1302);
  mesa33.add(nodes.Mesh6618_1303);
  mesa33.add(nodes.Mesh6618_1304);
  mesa33.add(nodes.Mesh6618_1305);
  mesa33.add(nodes.Mesh6618_1306);
  mesa33.add(nodes.Mesh6618_1307);
  mesa33.add(nodes.Mesh6618_1308);
  mesa33.add(nodes.Mesh6618_1309);
  mesa33.add(nodes.Mesh6618_1310);
  mesa33.add(nodes.Mesh6618_1311);
  mesa33.add(nodes.Mesh6618_1312);
  mesa33.add(nodes.Mesh6618_1313);


  mesa34.add(nodes.Mesh6618_1272);
  mesa34.add(nodes.Mesh6618_1273);
  mesa34.add(nodes.Mesh6618_1274);
  mesa34.add(nodes.Mesh6618_1275);
  mesa34.add(nodes.Mesh6618_1276);
  mesa34.add(nodes.Mesh6618_1277);
  mesa34.add(nodes.Mesh6618_1278);
  mesa34.add(nodes.Mesh6618_1279);
  mesa34.add(nodes.Mesh6618_1280);
  mesa34.add(nodes.Mesh6618_1281);
  mesa34.add(nodes.Mesh6618_1282);
  mesa34.add(nodes.Mesh6618_1283);
  mesa34.add(nodes.Mesh6618_1284);
  mesa34.add(nodes.Mesh6618_1285);
  mesa34.add(nodes.Mesh6618_1286);
  mesa34.add(nodes.Mesh6618_1287);
  mesa34.add(nodes.Mesh6618_1288);
  mesa34.add(nodes.Mesh6618_1289);
  mesa34.add(nodes.Mesh6618_1290);
  mesa34.add(nodes.Mesh6618_1291);
  mesa34.add(nodes.Mesh6618_1292);


  mesa35.add(nodes.Mesh6618_798);
  mesa35.add(nodes.Mesh6618_799);
  mesa35.add(nodes.Mesh6618_800);
  mesa35.add(nodes.Mesh6618_801);
  mesa35.add(nodes.Mesh6618_802);
  mesa35.add(nodes.Mesh6618_803);
  mesa35.add(nodes.Mesh6618_804);
  mesa35.add(nodes.Mesh6618_805);
  mesa35.add(nodes.Mesh6618_806);
  mesa35.add(nodes.Mesh6618_807);
  mesa35.add(nodes.Mesh6618_808);
  mesa35.add(nodes.Mesh6618_809);
  mesa35.add(nodes.Mesh6618_810);
  mesa35.add(nodes.Mesh6618_811);
  mesa35.add(nodes.Mesh6618_812);
  mesa35.add(nodes.Mesh6618_813);
  mesa35.add(nodes.Mesh6618_814);
  mesa35.add(nodes.Mesh6618_815);
  mesa35.add(nodes.Mesh6618_816);
  mesa35.add(nodes.Mesh6618_817);
  mesa35.add(nodes.Mesh6618_818);


  mesa36.add(nodes.Mesh6618_819);
  mesa36.add(nodes.Mesh6618_820);
  mesa36.add(nodes.Mesh6618_821);
  mesa36.add(nodes.Mesh6618_822);
  mesa36.add(nodes.Mesh6618_823);
  mesa36.add(nodes.Mesh6618_824);
  mesa36.add(nodes.Mesh6618_825);
  mesa36.add(nodes.Mesh6618_826);
  mesa36.add(nodes.Mesh6618_827);
  mesa36.add(nodes.Mesh6618_828);
  mesa36.add(nodes.Mesh6618_829);
  mesa36.add(nodes.Mesh6618_830);
  mesa36.add(nodes.Mesh6618_831);
  mesa36.add(nodes.Mesh6618_832);
  mesa36.add(nodes.Mesh6618_833);
  mesa36.add(nodes.Mesh6618_834);
  mesa36.add(nodes.Mesh6618_835);
  mesa36.add(nodes.Mesh6618_836);
  mesa36.add(nodes.Mesh6618_837);
  mesa36.add(nodes.Mesh6618_838);
  mesa36.add(nodes.Mesh6618_839);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.35, 3.48, -7.54]} rotation={[1.78, 0.45, -2.02]} scale={0.15}>
        <primitive object={mesa1} onClick = {() => handleMesaClick(mesa1.userData.id)}/>
        <primitive object={mesa2} onClick = {() => handleMesaClick(mesa2.userData.id)}/>
        <primitive object={mesa3} onClick = {() => handleMesaClick(mesa3.userData.id)}/>
        <primitive object={mesa4} onClick = {() => handleMesaClick(mesa4.userData.id)}/>
        <primitive object={mesa5} onClick = {() => handleMesaClick(mesa5.userData.id)}/>
        <primitive object={mesa6} onClick = {() => handleMesaClick(mesa6.userData.id)}/>
        <primitive object={mesa7} onClick = {() => handleMesaClick(mesa7.userData.id)}/>
        <primitive object={mesa8} onClick = {() => handleMesaClick(mesa8.userData.id)}/>
        <primitive object={mesa9} onClick = {() => handleMesaClick(mesa9.userData.id)}/>
        <primitive object={mesa10} onClick = {() => handleMesaClick(mesa10.userData.id)}/>
        <primitive object={mesa11} onClick = {() => handleMesaClick(mesa11.userData.id)}/>
        <primitive object={mesa12} onClick = {() => handleMesaClick(mesa12.userData.id)}/>
        <primitive object={mesa13} onClick = {() => handleMesaClick(mesa13.userData.id)}/>
        <primitive object={mesa14} onClick = {() => handleMesaClick(mesa14.userData.id)}/>
        <primitive object={mesa15} onClick = {() => handleMesaClick(mesa15.userData.id)}/>
        <primitive object={mesa16} onClick = {() => handleMesaClick(mesa16.userData.id)}/>
        <primitive object={mesa17} onClick = {() => handleMesaClick(mesa17.userData.id)}/>
        <primitive object={mesa18} onClick = {() => handleMesaClick(mesa18.userData.id)}/>
        <primitive object={mesa19} onClick = {() => handleMesaClick(mesa19.userData.id)}/>
        <primitive object={mesa20} onClick = {() => handleMesaClick(mesa20.userData.id)}/> 
        <primitive object={mesa21} onClick = {() => handleMesaClick(mesa21.userData.id)}/>
        <primitive object={mesa22} onClick = {() => handleMesaClick(mesa22.userData.id)}/>
        <primitive object={mesa23} onClick = {() => handleMesaClick(mesa23.userData.id)}/>
        <primitive object={mesa24} onClick = {() => handleMesaClick(mesa24.userData.id)}/>
        <primitive object={mesa25} onClick = {() => handleMesaClick(mesa25.userData.id)}/>
        <primitive object={mesa26} onClick = {() => handleMesaClick(mesa26.userData.id)}/>
        <primitive object={mesa27} onClick = {() => handleMesaClick(mesa27.userData.id)}/>
        <primitive object={mesa28} onClick = {() => handleMesaClick(mesa28.userData.id)}/>
        <primitive object={mesa29} onClick = {() => handleMesaClick(mesa29.userData.id)}/>
        <primitive object={mesa30} onClick = {() => handleMesaClick(mesa30.userData.id)}/>
        <primitive object={mesa31} onClick = {() => handleMesaClick(mesa31.userData.id)}/>
        <primitive object={mesa32} onClick = {() => handleMesaClick(mesa32.userData.id)}/>
        <primitive object={mesa33} onClick = {() => handleMesaClick(mesa33.userData.id)}/>
        <primitive object={mesa34} onClick = {() => handleMesaClick(mesa34.userData.id)}/>
        <primitive object={mesa35} onClick = {() => handleMesaClick(mesa35.userData.id)}/>
        <primitive object={mesa36} onClick = {() => handleMesaClick(mesa36.userData.id)}/>
        <mesh geometry={nodes.Mesh6618.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Mesh6618_1.geometry} material={materials['dbl_Group_036.005']} />
        <mesh geometry={nodes.Mesh6618_2.geometry} material={materials['dbl_Group_037.005']} />
        <mesh geometry={nodes.Mesh6618_3.geometry} material={materials['dbl_Group_038.005']} />
        <mesh geometry={nodes.Mesh6618_4.geometry} material={materials.dbl_Group_036} />
        <mesh geometry={nodes.Mesh6618_5.geometry} material={materials.dbl_Group_037} />
        <mesh geometry={nodes.Mesh6618_6.geometry} material={materials.dbl_Group_038} />
        <mesh geometry={nodes.Mesh6618_7.geometry} material={materials['dbl_Group_036.001']} />
        <mesh geometry={nodes.Mesh6618_8.geometry} material={materials['dbl_Group_037.001']} />
        <mesh geometry={nodes.Mesh6618_9.geometry} material={materials['dbl_Group_038.001']} />
        <mesh geometry={nodes.Mesh6618_10.geometry} material={materials['dbl_Group_036.002']} />
        <mesh geometry={nodes.Mesh6618_11.geometry} material={materials['dbl_Group_037.002']} />
        <mesh geometry={nodes.Mesh6618_12.geometry} material={materials['dbl_Group_038.002']} />
        <mesh geometry={nodes.Mesh6618_13.geometry} material={materials['dbl_Group_036.003']} />
        <mesh geometry={nodes.Mesh6618_14.geometry} material={materials['dbl_Group_037.003']} />
        <mesh geometry={nodes.Mesh6618_15.geometry} material={materials['dbl_Group_038.003']} />
        <mesh geometry={nodes.Mesh6618_16.geometry} material={materials['dbl_Group_036.004']} />
        <mesh geometry={nodes.Mesh6618_17.geometry} material={materials['dbl_Group_037.004']} />
        <mesh geometry={nodes.Mesh6618_18.geometry} material={materials['dbl_Group_038.004']} />
        <mesh geometry={nodes.Mesh6618_19.geometry} material={materials['dbl_Door_Glass_Commercial_001.001']} />
        <mesh geometry={nodes.Mesh6618_20.geometry} material={materials['dbl_Door_Glass_Commercial_002.001']} />
        <mesh geometry={nodes.Mesh6618_21.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Mesh6618_22.geometry} material={materials.dbl_Group_001} />
        <mesh geometry={nodes.Mesh6618_23.geometry} material={materials.dbl_Group_002} />
        <mesh geometry={nodes.Mesh6618_24.geometry} material={materials['dbl_Group_003.001']} />
        <mesh geometry={nodes.Mesh6618_25.geometry} material={materials.dbl_Group_004} />
        <mesh geometry={nodes.Mesh6618_26.geometry} material={materials.dbl_Group_005} />
        <mesh geometry={nodes.Mesh6618_27.geometry} material={materials.dbl_Group_006} />
        <mesh geometry={nodes.Mesh6618_28.geometry} material={materials.dbl_Group_007} />
        <mesh geometry={nodes.Mesh6618_29.geometry} material={materials['dbl_Group_008.132']} />
        <mesh geometry={nodes.Mesh6618_30.geometry} material={materials.dbl_Group_009} />
        <mesh geometry={nodes.Mesh6618_31.geometry} material={materials.dbl_Group_010} />
        <mesh geometry={nodes.Mesh6618_32.geometry} material={materials.dbl_Group_011} />
        <mesh geometry={nodes.Mesh6618_33.geometry} material={materials.dbl_Group_012} />
        <mesh geometry={nodes.Mesh6618_34.geometry} material={materials.dbl_Group_013} />
        <mesh geometry={nodes.Mesh6618_35.geometry} material={materials.dbl_Group_014} />
        <mesh geometry={nodes.Mesh6618_36.geometry} material={materials.dbl_Group_015} />
        <mesh geometry={nodes.Mesh6618_37.geometry} material={materials.dbl_Group_016} />
        <mesh geometry={nodes.Mesh6618_38.geometry} material={materials.grupo003} />
        <mesh geometry={nodes.Mesh6618_39.geometry} material={materials.dbl_Group_018} />
        <mesh geometry={nodes.Mesh6618_40.geometry} material={materials.dbl_Group_019} />
        <mesh geometry={nodes.Mesh6618_41.geometry} material={materials['dbl_Group_020.269']} />
        <mesh geometry={nodes.Mesh6618_42.geometry} material={materials['piso.002']} />
        <mesh geometry={nodes.Mesh6618_43.geometry} material={materials.dbl_Group_022} />
        <mesh geometry={nodes.Mesh6618_44.geometry} material={materials.dbl_Group_023} />
        <mesh geometry={nodes.Mesh6618_45.geometry} material={materials.dbl_Group_024} />
        <mesh geometry={nodes.Mesh6618_46.geometry} material={materials.dbl_Group_025} />
        <mesh geometry={nodes.Mesh6618_47.geometry} material={materials['dbl_Group_026.011']} />
        <mesh geometry={nodes.Mesh6618_48.geometry} material={materials.dbl_Group_027} />
        <mesh geometry={nodes.Mesh6618_49.geometry} material={materials['dbl_Group_028.132']} />
        <mesh geometry={nodes.Mesh6618_50.geometry} material={materials.dbl_Group_029} />
        <mesh geometry={nodes.Mesh6618_51.geometry} material={materials.dbl_Group_030} />
        <mesh geometry={nodes.Mesh6618_52.geometry} material={materials.dbl_Group_031} />
        <mesh geometry={nodes.Mesh6618_53.geometry} material={materials.dbl_Group_032} />
        <mesh geometry={nodes.Mesh6618_54.geometry} material={materials.dbl_Group_034} />
        <mesh geometry={nodes.Mesh6618_55.geometry} material={materials.dbl_Group_035} />
        <mesh geometry={nodes.Mesh6618_56.geometry} material={materials['dbl_Group_007.001']} />
        <mesh geometry={nodes.Mesh6618_57.geometry} material={materials['dbl_Group_017.003']} />
        <mesh geometry={nodes.Mesh6618_58.geometry} material={materials['dbl_Group_011.002']} />
        <mesh geometry={nodes.Mesh6618_59.geometry} material={materials['dbl_Group_020.274']} />
        <mesh geometry={nodes.Mesh6618_60.geometry} material={materials['dbl_Group_005.002']} />
        <mesh geometry={nodes.Mesh6618_61.geometry} material={materials['dbl_Group_012.002']} />
        <mesh geometry={nodes.Mesh6618_62.geometry} material={materials['dbl_Group_012.003']} />
        <mesh geometry={nodes.Mesh6618_63.geometry} material={materials['dbl_Group_016.002']} />
        <mesh geometry={nodes.Mesh6618_64.geometry} material={materials['dbl_Group_016.003']} />
        <mesh geometry={nodes.Mesh6618_65.geometry} material={materials['dbl_Group_005.003']} />
        <mesh geometry={nodes.Mesh6618_66.geometry} material={materials['dbl_Group_007.002']} />
        <mesh geometry={nodes.Mesh6618_67.geometry} material={materials['dbl_Group_007.003']} />
        <mesh geometry={nodes.Mesh6618_68.geometry} material={materials['dbl_Group_020.271']} />
        <mesh geometry={nodes.Mesh6618_69.geometry} material={materials['dbl_Group_020.273']} />
        <mesh geometry={nodes.Mesh6618_70.geometry} material={materials['dbl_Group_020.272']} />
        <mesh geometry={nodes.Mesh6618_71.geometry} material={materials['dbl_Group_011.003']} />
        <mesh geometry={nodes.Mesh6618_72.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Mesh6618_73.geometry} material={materials['dbl_Group_026.009']} />
        <mesh geometry={nodes.Mesh6618_74.geometry} material={materials.dbl_Group_047} />
        <mesh geometry={nodes.Mesh6618_75.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Mesh6618_76.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh6618_77.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Mesh6618_78.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Mesh6618_79.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Mesh6618_80.geometry} material={materials.dbl_Group_020} />
        <mesh geometry={nodes.Mesh6618_81.geometry} material={materials.dbl_Door_Glass_Commercial_002} />
        <mesh geometry={nodes.Mesh6618_82.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Mesh6618_83.geometry} material={materials['Material.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/restaurante/Mesas.gltf')
